arvestust/urls.py
# arvestust:urls
from django.urls import include, path
from .views.urls import urlpatterns

app_name = 'arvestust'

arvestust/views/comment_detail.py
from django.utils import timezone
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import path
from ..models import Comment
from .urls import urlpatterns


class CommentDetailView(LoginRequiredMixin, DetailView):
    model = Comment
    context_object_name = 'comment'
    template_name = 'comment_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


urlpatterns.append(
    path('comments/<slug:slug>', CommentDetailView.as_view(), name='comment-detail')
)

arvestust/views/comment_list.py
from django.utils import timezone
from django.views.generic import ListView, CreateView
from django.urls import path
from django.contrib.auth.mixins import LoginRequiredMixin
from .urls import urlpatterns
from ..models import Comment
from ..forms import CommentForm


class CommentListView(LoginRequiredMixin, ListView, CreateView):
    model = Comment
    context_object_name = 'comments'
    template_name = 'comment_list.html'
    form_class = CommentForm
    paginate_by = 50

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


urlpatterns.append(
    path('comments/', CommentListView.as_view(), name='comment-list')
)

arvestust/views/file_detail.py
from django.utils import timezone
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import path
from .urls import urlpatterns
from ..models import File
from ..forms import FileForm


class FileDetailView(LoginRequiredMixin, DetailView):
    model = File
    context_object_name = 'file'
    template_name = 'file_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


urlpatterns.append(
    path('files/<slug:slug>', FileDetailView.as_view(), name='file-detail')
)

arvestust/views/file_list.py
from django.utils import timezone
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import path
from .urls import urlpatterns
from ..models import File


class FileListView(LoginRequiredMixin, ListView):
    model = File
    context_object_name = 'files'
    template_name = 'file_list.html'
    paginate_by = 20

    def get_queryset(self):
        return File.objects.filter(
            uploaded_by=self.request.user
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


urlpatterns.append(
    path('files/', FileListView.as_view(), name='file-list')
)

arvestust/views/image_detail.py
from django.views.generic import DetailView
from django.urls import path
from .urls import urlpatterns
from ..models import Image


class ImageDetailView(DetailView):
    model = Image
    context_object_name = 'image'
    template_name = 'image_detail.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


urlpatterns.append(
    path('images/<slug:slug>', ImageDetailView.as_view(), name='image-detail')
)

arvestust/views/image_list.py
from django.views.generic import ListView
from django.urls import path
from .urls import urlpatterns
from ..models import Image


class ImageListView(ListView):
    model = Image
    context_object_name = 'images'
    template_name = 'image_list.html'
    paginate_by = 20
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


urlpatterns.append(
    path('images/', ImageListView.as_view(), name='image-list')
)

arvestust/views/tag_detail.py
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import path
from .urls import urlpatterns
from ..models import Tag


class TagDetailView(LoginRequiredMixin, DetailView):
    model = Tag
    context_object_name = 'tag'
    template_name = 'tag_detail.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


urlpatterns.append(
    path('tags/<slug:slug>', TagDetailView.as_view(), name='tag-detail')
)

arvestust/views/tag_list.py
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import path
from .urls import urlpatterns
from ..models import Tag


class TagListView(LoginRequiredMixin, ListView):
    model = Tag
    context_object_name = 'tags'
    template_name = 'tag_list.html'
    paginate_by = 100

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


urlpatterns.append(
    path('tags/', TagListView.as_view(), name='tag-list')
)

arvestust/templates/arvestust.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>{% block title %}Django Arvestust{% endblock %}</title>
</head>
<body class="bg-light">
    <!-- Content -->
    {% block content %}
    {% endblock content %}

<!-- Vue.js -->
<script src="https://unpkg.com/vue"></script>
<script src="https://unpkg.com/vue-router"></script>
<script src="https://unpkg.com/axios@0.19.0/dist/axios.min.js"></script>

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

{% block scripts %}
{% endblock %}
</body>
</html>

arvestust/templates/comment_detail.html
{% extends 'arvestust.html' %}
{% load cache %}

{% comment %}
    Describe the template here.
{% endcomment %}

{% block content %}
    <p>
        <a href="{{ object.content_object.get_absolute_url }}">Parent Object</a>
    </p>
    <h4 class="text-bold">{{ object }}</h4>
    <div class="content-area">
        {{ object.content }}
    </div>
{% endblock %}

arvestust/templates/comment_list.html
{% extends 'arvestust.html' %}
{% load cache %}

{% comment %}
    Describe the template here.
{% endcomment %}

{% block content %}
<div class="container">
    <h2 class="text-bold">comments</h2>

    <div class="row">
        {% for object in object_list %}
        <div class="col-md-12">
            <a href="{{ object.get_absolute_url }}">{{ object.content }}</a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

arvestust/templates/file_list.html
{% extends 'arvestust.html' %}
{% load arvestust %}
{% load static %}

{% comment %}
    Describe the template here.
{% endcomment %}

{% block main-stylesheet %}
    <link rel="stylesheet" href="{% static 'assets/css/dashforge.filemgr.css' %}">
{% endblock %}

{% block page-class %}app-filemgr{% endblock page-class %}

{% block aside %}aside-filemgr{% endblock aside %}

{% block search %}Search files{% endblock %}

{% block content %}
    <div id="files-app" class="filemgr-wrapper filemgr-wrapper-two">
        <div class="filemgr-sidebar"></div>

        <div class="filemgr-content">
            [[ content ]]
        </div>
    </div>
{% endblock content %}

{% block scripts %}
<script>
    const app = new Vue({
      el: "#files-app",
      delimiters: ["[[", "]]"],
      data () {
          return {
              content: [{{ files|json_dump }}]
          }
      },
    });
</script>
{% endblock %}

arvestust/templates/image_detail.html
{% extends 'arvestust.html' %}
{% load cache %}

{% comment %}
    Describe the template here.
{% endcomment %}

{% block body %}
    <h2>{{ object }}</h2>
{% endblock body %}

{% block scripts %}{% endblock scripts %}

arvestust/templates/image_list.html
{% extends 'arvestust.html' %}
{% load cache %}

{% comment %}
    Describe the template here.
{% endcomment %}

{% block header %}{% endblock header %}
{% block body %}

    <h2>images</h2>

    <ul>
    {% for object in object_list %}
    <li>
        <a href="{{ object.get_absolute_url }}">{{ object }}</a>
    </li>
    {% endfor %}
    </ul>
{% endblock body %}

{% block footer %}{% endblock footer %}

{% block scripts %}{% endblock scripts %}

arvestust/templates/tag_detail.html
{% extends 'arvestust.html' %}
{% load cache %}

{% comment %}
    Describe the template here.
{% endcomment %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="p-0 breadcrumb bg-light">
            <li class="breadcrumb-item">
                <a href="{% url 'arvestust:tag-list' %}">Tags</a>
            </li>
            <li class="breadcrumb-item active">{{ tag.content }}</li>
        </ol>
    </nav>

    <h2 class="text-bold pb-3">{{ tag }}</h2>

    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">slug</th>
          <th scope="col">Content</th>
        </tr>
      </thead>
      <tbody>
    {% for object in tag.projects.all %}
        <tr>
          <th scope="row">{{ object.id }}</th>
          <td>
              <a href="{{ object.get_absolute_url }}">
                {{ object.slug }}
              </a>
          </td>
          <td>{{ object.slug }}</td>
        </tr>
    {% endfor %}
      </tbody>
    </table>

{% endblock content %}

arvestust/templates/tag_list.html
{% extends 'arvestust.html' %}
{% load cache %}
{% load i18n %}

{% comment %}
    Describe the template here.
{% endcomment %}

{% block content %}
    <h2 class="text-bold pb-3">Tags</h2>

    <div class="card-columns">
    {% for tag in object_list %}
        <div class="card border-muted">
            <div class="card-body">
                <div class="d-flex flex-row justify-content-start">
                    <h5 class="card-title">
                        <a href="{{ tag.get_absolute_url }}">{{ tag.content }}</a>
                    </h5>
                </div>
                <div class="card-text">
                    <p>
                        <small class="text-muted">
                            {% blocktrans with time=tag.created_at|timesince %}
                            Created {{ time }} ago
                            {% endblocktrans %}
                        </small>
                    </p>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}